services:
  - type: web
    name: bip353-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: POWERDNS_API_URL
        sync: false
      - key: POWERDNS_API_KEY
        sync: false
      - key: POWERDNS_SERVER_ID
        value: localhost
      - key: DNS_ZONE
        value: easybitcoinaddress.me
      - key: DNS_TTL
        value: 300
      - key: AUTH_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: info
